# Generated by Django 4.2.5 on 2023-09-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('games_played', models.IntegerField(default=0)),
                ('ppg', models.FloatField(default=0.0)),
                ('rpg', models.FloatField(default=0.0)),
                ('apg', models.FloatField(default=0.0)),
                ('fg_pct', models.FloatField(default=0.0)),
                ('fg3_pct', models.FloatField(default=0.0)),
                ('ft_pct', models.FloatField(default=0.0)),
            ],
        ),
    ]
