# Generated by Django 4.2.5 on 2023-10-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('suffix', models.CharField(max_length=5)),
                ('pos', models.CharField(max_length=2)),
                ('team', models.CharField(max_length=3)),
                ('gp', models.IntegerField(default=0)),
                ('mpg', models.FloatField(default=0.0)),
                ('fg_pct', models.FloatField(default=0.0)),
                ('ft_pct', models.FloatField(default=0.0)),
                ('threes_made', models.FloatField(default=0.0)),
                ('rpg', models.FloatField(default=0.0)),
                ('apg', models.FloatField(default=0.0)),
                ('stpg', models.FloatField(default=0.0)),
                ('blkpg', models.FloatField(default=0.0)),
                ('topg', models.FloatField(default=0.0)),
                ('ppg', models.FloatField(default=0.0)),
                ('salary', models.IntegerField(default=0.0)),
            ],
        ),
    ]
